//! End to end against a real ffmpeg.
//!
//! Ignored by default so `cargo test` passes on a machine without ffmpeg. CI
//! installs it and runs these with `--include-ignored`.

use karui_core::batch::{self, Event};
use karui_core::options::{Audio, Codec, CompressOptions};
use karui_core::plan::{partial_path, plan};
use karui_core::preview::{compare, fresh_dir, thumbnail, Request, Stage};
use karui_core::probe::probe;
use karui_core::tools::{command, Tools};
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("karui-e2e-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

/// A two-second 320×240 clip with a tone, generated by ffmpeg itself. The
/// name carries a space, a quote, and a colon, each of which broke the
/// original script.
fn sample(tools: &Tools, dir: &Path, width: u32, height: u32) -> PathBuf {
    let path = dir.join(format!("it's a clip:{width}x{height}.mov"));
    let status = command(&tools.ffmpeg)
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
        ])
        .arg(format!("testsrc2=size={width}x{height}:rate=60:duration=2"))
        .args(["-f", "lavfi", "-i", "sine=frequency=440:duration=2"])
        .args([
            "-c:v",
            "mpeg4",
            "-q:v",
            "2",
            "-c:a",
            "pcm_s16le",
            "-shortest",
        ])
        .arg(format!("file:{}", path.display()))
        .status()
        .expect("run ffmpeg");
    assert!(status.success(), "could not generate the sample clip");
    path
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn compresses_a_batch_end_to_end() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("batch");
    let even = sample(&tools, &dir, 320, 240);
    let odd = sample(&tools, &dir, 321, 241);

    let opts = CompressOptions {
        codec: Codec::H264,
        max_fps: Some(30),
        audio: Audio::Copy,
        ..Default::default()
    };
    let jobs = plan(&[even, odd], None, false);
    let cancel = AtomicBool::new(false);
    let mut events = Vec::new();
    let summary = batch::run(&tools, &jobs, &opts, &cancel, |e| events.push(e));

    assert_eq!(summary.succeeded, 2, "events: {events:?}");
    assert!(events.iter().any(|e| matches!(e, Event::Progress { .. })));
    // The live monitor's numbers arrive from a real encode.
    assert!(events.iter().any(|e| matches!(
        e,
        Event::Progress {
            frame: Some(_),
            total_frames: Some(_),
            written_bytes: Some(_),
            ..
        }
    )));

    for job in &jobs {
        assert!(job.output.exists());
        assert!(!partial_path(&job.output).exists());
        let info = probe(&tools, &job.output).expect("probe output");
        assert_eq!(info.video_codec, "h264");
        assert_eq!(info.width % 2, 0);
        assert!(info.fps.expect("fps") <= 30.5);
        // PCM cannot go in MP4, so "copy" fell back to AAC.
        assert_eq!(info.audio_codec.as_deref(), Some("aac"));
        let modified = |p: &Path| {
            std::fs::metadata(p)
                .and_then(|m| m.modified())
                .expect("mtime")
        };
        assert_eq!(modified(&job.output), modified(&job.input));
    }
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn a_failed_encode_leaves_no_files() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("broken");
    let fake = dir.join("broken.mp4");
    std::fs::write(&fake, b"not a video").expect("write");

    let jobs = plan(&[fake], None, false);
    let cancel = AtomicBool::new(false);
    let summary = batch::run(&tools, &jobs, &CompressOptions::default(), &cancel, |_| {});

    assert_eq!(summary.failed, 1);
    assert!(!jobs[0].output.exists());
    assert!(!partial_path(&jobs[0].output).exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn previews_a_sample_and_a_finished_output() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("preview");
    let clip = sample(&tools, &dir, 321, 241);
    let cancel = AtomicBool::new(false);
    let opts = CompressOptions {
        codec: Codec::H264,
        crf: Some(40),
        max_resolution: Some(120),
        ..Default::default()
    };

    let request = Request {
        input: clip.clone(),
        output: None,
        options: opts.clone(),
        at_secs: 99.0,
    };
    let work = fresh_dir(&dir.join("preview")).expect("work dir");
    let mut stages = Vec::new();
    let sampled = compare(&tools, &request, &work, &cancel, &mut |stage| {
        stages.push(stage)
    })
    .expect("sample comparison");
    // The original is reported before the sample encode's progress.
    assert!(matches!(stages.first(), Some(Stage::Original { .. })));
    assert!(stages.iter().any(|s| matches!(s, Stage::Sampling { .. })));
    assert!(!sampled.from_output);
    // Clamped inside the two-second clip.
    assert!(sampled.at_secs <= 1.5);
    // Both stills at the source's size, the encode at its capped one.
    let source = probe(&tools, &clip).expect("probe source");
    assert_eq!((sampled.width, sampled.height), source.display_size());
    assert_eq!(sampled.encoded_height, 120);
    assert!(sampled.original.exists() && sampled.compressed.exists());
    let ssim = sampled.ssim.expect("ssim");
    assert!(ssim > 0.0 && ssim < 1.0, "ssim {ssim}");
    assert!(sampled.rating.is_some());
    assert!(sampled.estimated_bytes.expect("estimate") > 0);

    let jobs = plan(&[clip], None, false);
    let summary = batch::run(&tools, &jobs, &opts, &cancel, |_| {});
    assert_eq!(summary.succeeded, 1);
    let request = Request {
        output: Some(jobs[0].output.clone()),
        at_secs: 1.0,
        ..request
    };
    let work = fresh_dir(&dir.join("preview")).expect("work dir");
    let finished =
        compare(&tools, &request, &work, &cancel, &mut |_| {}).expect("output comparison");
    assert!(finished.from_output);
    assert_eq!(finished.estimated_bytes, None);
    assert_eq!(finished.video_codec, "h264");
    assert!(finished.compressed.exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn thumbnails_an_odd_sized_clip() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("thumbnail");
    let clip = sample(&tools, &dir, 321, 241);
    let info = probe(&tools, &clip).expect("probe");
    let jpeg = thumbnail(&tools, &clip, &info).expect("thumbnail");
    // JPEG start-of-image marker.
    assert_eq!(&jpeg[..2], &[0xFF, 0xD8]);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn benchmarks_an_encode_rate_quickly() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let opts = CompressOptions {
        codec: Codec::H264,
        preset: karui_core::options::Preset::Veryfast,
        ..Default::default()
    };
    let cancel = AtomicBool::new(false);
    let started = std::time::Instant::now();
    let rate = karui_core::estimate::benchmark(&tools, &opts, &cancel).expect("benchmark");
    // Any machine that can run CI encodes 720p faster than 1 Mpx/s.
    assert!(rate > 1e6, "rate {rate}");
    assert!(
        started.elapsed().as_secs() < 20,
        "took {:?}",
        started.elapsed()
    );

    cancel.store(true, std::sync::atomic::Ordering::Relaxed);
    assert!(matches!(
        karui_core::estimate::benchmark(&tools, &opts, &cancel),
        Err(karui_core::Error::Cancelled)
    ));
}
