//! End to end against a real ffmpeg.
//!
//! Ignored by default so `cargo test` passes on a machine without ffmpeg. CI
//! installs it and runs these with `--include-ignored`.

use karui_core::batch::{self, Event};
use karui_core::options::{Audio, Codec, CompressOptions};
use karui_core::plan::{partial_path, plan};
use karui_core::probe::probe;
use karui_core::tools::{command, Tools};
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("karui-e2e-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

/// A two-second 320×240 clip with a tone, generated by ffmpeg itself. The
/// name carries a space, a quote, and a colon, each of which broke the
/// original script.
fn sample(tools: &Tools, dir: &Path, width: u32, height: u32) -> PathBuf {
    let path = dir.join(format!("it's a clip:{width}x{height}.mov"));
    let status = command(&tools.ffmpeg)
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
        ])
        .arg(format!("testsrc2=size={width}x{height}:rate=60:duration=2"))
        .args(["-f", "lavfi", "-i", "sine=frequency=440:duration=2"])
        .args([
            "-c:v",
            "mpeg4",
            "-q:v",
            "2",
            "-c:a",
            "pcm_s16le",
            "-shortest",
        ])
        .arg(format!("file:{}", path.display()))
        .status()
        .expect("run ffmpeg");
    assert!(status.success(), "could not generate the sample clip");
    path
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn compresses_a_batch_end_to_end() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("batch");
    let even = sample(&tools, &dir, 320, 240);
    let odd = sample(&tools, &dir, 321, 241);

    let opts = CompressOptions {
        codec: Codec::H264,
        max_fps: Some(30),
        audio: Audio::Copy,
        ..Default::default()
    };
    let jobs = plan(&[even, odd], None, false);
    let cancel = AtomicBool::new(false);
    let mut events = Vec::new();
    let summary = batch::run(&tools, &jobs, &opts, &cancel, |e| events.push(e));

    assert_eq!(summary.succeeded, 2, "events: {events:?}");
    assert!(events.iter().any(|e| matches!(e, Event::Progress { .. })));

    for job in &jobs {
        assert!(job.output.exists());
        assert!(!partial_path(&job.output).exists());
        let info = probe(&tools, &job.output).expect("probe output");
        assert_eq!(info.video_codec, "h264");
        assert_eq!(info.width % 2, 0);
        assert!(info.fps.expect("fps") <= 30.5);
        // PCM cannot go in MP4, so "copy" fell back to AAC.
        assert_eq!(info.audio_codec.as_deref(), Some("aac"));
    }
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn a_failed_encode_leaves_no_files() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("broken");
    let fake = dir.join("broken.mp4");
    std::fs::write(&fake, b"not a video").expect("write");

    let jobs = plan(&[fake], None, false);
    let cancel = AtomicBool::new(false);
    let summary = batch::run(&tools, &jobs, &CompressOptions::default(), &cancel, |_| {});

    assert_eq!(summary.failed, 1);
    assert!(!jobs[0].output.exists());
    assert!(!partial_path(&jobs[0].output).exists());
    let _ = std::fs::remove_dir_all(&dir);
}
