//! End to end against a real ffmpeg.
//!
//! Ignored by default so `cargo test` passes on a machine without ffmpeg. CI
//! installs it and runs these with `--include-ignored`.

use karui_core::batch::{self, Event};
use karui_core::options::{Audio, Codec, CompressOptions};
use karui_core::plan::{partial_path, plan};
use karui_core::preview::{compare, fresh_dir, thumbnail, Request, Stage};
use karui_core::probe::probe;
use karui_core::tools::{command, Tools};
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("karui-e2e-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

/// A two-second 320×240 clip with a tone, generated by ffmpeg itself. The
/// name carries a space, a quote, and a colon, each of which broke the
/// original script.
fn sample(tools: &Tools, dir: &Path, width: u32, height: u32) -> PathBuf {
    let path = dir.join(format!("it's a clip:{width}x{height}.mov"));
    let status = command(&tools.ffmpeg)
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
        ])
        .arg(format!("testsrc2=size={width}x{height}:rate=60:duration=2"))
        .args(["-f", "lavfi", "-i", "sine=frequency=440:duration=2"])
        .args([
            "-c:v",
            "mpeg4",
            "-q:v",
            "2",
            "-c:a",
            "pcm_s16le",
            "-shortest",
        ])
        .arg(format!("file:{}", path.display()))
        .status()
        .expect("run ffmpeg");
    assert!(status.success(), "could not generate the sample clip");
    path
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn compresses_a_batch_end_to_end() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("batch");
    let even = sample(&tools, &dir, 320, 240);
    let odd = sample(&tools, &dir, 321, 241);

    let opts = CompressOptions {
        codec: Codec::H264,
        max_fps: Some(30),
        audio: Audio::Copy,
        ..Default::default()
    };
    let jobs = plan(&[even, odd], None, false);
    let cancel = AtomicBool::new(false);
    let mut events = Vec::new();
    let summary = batch::run(&tools, &jobs, &opts, &cancel, |e| events.push(e));

    assert_eq!(summary.succeeded, 2, "events: {events:?}");
    assert!(events.iter().any(|e| matches!(e, Event::Progress { .. })));
    // The live monitor's numbers arrive from a real encode.
    assert!(events.iter().any(|e| matches!(
        e,
        Event::Progress {
            frame: Some(_),
            total_frames: Some(_),
            written_bytes: Some(_),
            ..
        }
    )));

    for job in &jobs {
        assert!(job.output.exists());
        assert!(!partial_path(&job.output).exists());
        let info = probe(&tools, &job.output).expect("probe output");
        assert_eq!(info.video_codec, "h264");
        assert_eq!(info.width % 2, 0);
        assert!(info.fps.expect("fps") <= 30.5);
        // PCM cannot go in MP4, so "copy" fell back to AAC.
        assert_eq!(info.audio_codec.as_deref(), Some("aac"));
        let modified = |p: &Path| {
            std::fs::metadata(p)
                .and_then(|m| m.modified())
                .expect("mtime")
        };
        assert_eq!(modified(&job.output), modified(&job.input));
    }
    let _ = std::fs::remove_dir_all(&dir);
}

/// A clip made by ffmpeg from `inputs` (lavfi graphs) and encoder `args`.
fn generate(tools: &Tools, path: &Path, inputs: &[&str], args: &[&str]) {
    let mut cmd = command(&tools.ffmpeg);
    cmd.args(["-hide_banner", "-loglevel", "error", "-y"]);
    for input in inputs {
        cmd.args(["-f", "lavfi", "-i", input]);
    }
    let status = cmd
        .args(args)
        .arg(format!("file:{}", path.display()))
        .status()
        .expect("run ffmpeg");
    assert!(status.success(), "could not generate {}", path.display());
}

/// The MD5 of a file's audio packets, which match only if they were copied.
fn audio_md5(tools: &Tools, path: &Path) -> String {
    let output = command(&tools.ffmpeg)
        .args(["-hide_banner", "-loglevel", "error", "-i"])
        .arg(format!("file:{}", path.display()))
        .args(["-map", "0:a:0", "-c", "copy", "-f", "md5", "-"])
        .output()
        .expect("run ffmpeg");
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn keeps_the_original_when_compressing_would_not_shrink_it() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("kept");
    // Already squeezed far harder than CRF 12 will be.
    let clip = dir.join("tiny.mp4");
    generate(
        &tools,
        &clip,
        &["testsrc2=size=320x240:rate=30:duration=2"],
        &["-c:v", "libx264", "-crf", "45"],
    );
    let opts = CompressOptions {
        codec: Codec::H264,
        crf: Some(12),
        ..Default::default()
    };
    let cancel = AtomicBool::new(false);

    let beside = plan(std::slice::from_ref(&clip), None, false);
    let mut events = Vec::new();
    let summary = batch::run(&tools, &beside, &opts, &cancel, |e| events.push(e));
    assert_eq!(
        (summary.succeeded, summary.kept),
        (0, 1),
        "events: {events:?}"
    );
    assert_eq!(summary.output_bytes, 0);
    assert!(events.iter().any(|e| matches!(
        e,
        Event::KeptOriginal { input_bytes, output_bytes, .. } if output_bytes >= input_bytes
    )));
    assert!(!beside[0].output.exists());
    assert!(!partial_path(&beside[0].output).exists());
    assert!(clip.exists());

    // Sent to another folder, it is written however it came out.
    let elsewhere = plan(std::slice::from_ref(&clip), Some(&dir.join("out")), false);
    let summary = batch::run(&tools, &elsewhere, &opts, &cancel, |_| {});
    assert_eq!((summary.succeeded, summary.kept), (1, 0));
    assert!(elsewhere[0].output.exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn copies_aac_already_small_and_halves_mono() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("audio");
    let video = "testsrc2=size=320x240:rate=30:duration=3";
    // Noise, not a tone: ffmpeg 4.4's AAC encoder put a "256k" sine at 65k,
    // which is rightly copied. Noise spends the bitrate it is given.
    let noise = "anoisesrc=duration=3:color=pink:amplitude=0.5";
    let small = dir.join("small aac.mp4");
    generate(
        &tools,
        &small,
        &[video, noise],
        &[
            "-c:v",
            "libx264",
            "-ac",
            "2",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-shortest",
        ],
    );
    let large = dir.join("large aac.mp4");
    generate(
        &tools,
        &large,
        &[video, noise],
        &[
            "-c:v",
            "libx264",
            "-ac",
            "2",
            "-c:a",
            "aac",
            "-b:a",
            "256k",
            "-shortest",
        ],
    );
    let mono = dir.join("mono pcm.mov");
    generate(
        &tools,
        &mono,
        &[video, "sine=frequency=440:duration=3"],
        &[
            "-c:v",
            "libx264",
            "-ac",
            "1",
            "-c:a",
            "pcm_s16le",
            "-shortest",
        ],
    );

    let jobs = plan(
        &[small.clone(), large.clone(), mono.clone()],
        Some(&dir.join("out")),
        false,
    );
    let cancel = AtomicBool::new(false);
    let summary = batch::run(&tools, &jobs, &CompressOptions::default(), &cancel, |_| {});
    assert_eq!(summary.succeeded, 3);

    // Copied untouched, packet for packet.
    assert_eq!(
        audio_md5(&tools, &jobs[0].output),
        audio_md5(&tools, &small)
    );
    // Re-encoded down to 128k.
    assert_ne!(
        audio_md5(&tools, &jobs[1].output),
        audio_md5(&tools, &large)
    );
    let bitrate = |path: &Path| {
        probe(&tools, path)
            .expect("probe")
            .audio_bitrate
            .expect("bitrate")
    };
    assert!(
        bitrate(&jobs[1].output) <= 140_000,
        "{}",
        bitrate(&jobs[1].output)
    );
    // Mono PCM becomes 64k AAC, not 128k.
    let out = probe(&tools, &jobs[2].output).expect("probe");
    assert_eq!(out.audio_codec.as_deref(), Some("aac"));
    assert_eq!(out.audio_channels, Some(1));
    assert!(
        bitrate(&jobs[2].output) <= 70_000,
        "{}",
        bitrate(&jobs[2].output)
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn deinterlaces_interlaced_footage() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("interlaced");
    // 50 fields a second woven into 25 top-field-first frames, as 1080i50
    // from a camcorder is, and in the camcorder's MPEG-TS: ffprobe 4.4 reads
    // the field order of H.264 there but reports it unknown inside MP4.
    let clip = dir.join("camcorder 50i.mts");
    generate(
        &tools,
        &clip,
        &["testsrc2=size=320x240:rate=50:duration=2"],
        &[
            "-vf",
            "interlace=scan=tff",
            "-c:v",
            "libx264",
            "-flags",
            "+ildct+ilme",
            "-x264-params",
            "tff=1",
        ],
    );
    let source = probe(&tools, &clip).expect("probe");
    assert!(source.interlaced);

    let jobs = plan(&[clip], Some(&dir.join("out")), false);
    let cancel = AtomicBool::new(false);
    let summary = batch::run(&tools, &jobs, &CompressOptions::default(), &cancel, |_| {});
    assert_eq!(summary.succeeded, 1);
    let out = probe(&tools, &jobs[0].output).expect("probe output");
    assert!(!out.interlaced);
    // One frame out per frame in.
    assert!((out.fps.expect("fps") - 25.0).abs() < 0.1);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn a_failed_encode_leaves_no_files() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("broken");
    let fake = dir.join("broken.mp4");
    std::fs::write(&fake, b"not a video").expect("write");

    let jobs = plan(&[fake], None, false);
    let cancel = AtomicBool::new(false);
    let summary = batch::run(&tools, &jobs, &CompressOptions::default(), &cancel, |_| {});

    assert_eq!(summary.failed, 1);
    assert!(!jobs[0].output.exists());
    assert!(!partial_path(&jobs[0].output).exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn previews_a_sample_and_a_finished_output() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("preview");
    let clip = sample(&tools, &dir, 321, 241);
    let cancel = AtomicBool::new(false);
    let opts = CompressOptions {
        codec: Codec::H264,
        crf: Some(40),
        max_resolution: Some(120),
        ..Default::default()
    };

    let request = Request {
        input: clip.clone(),
        output: None,
        options: opts.clone(),
        at_secs: 99.0,
    };
    let work = fresh_dir(&dir.join("preview")).expect("work dir");
    let mut stages = Vec::new();
    let sampled = compare(&tools, &request, &work, &cancel, &mut |stage| {
        stages.push(stage)
    })
    .expect("sample comparison");
    // The original is reported before the sample encode's progress.
    assert!(matches!(stages.first(), Some(Stage::Original { .. })));
    assert!(stages.iter().any(|s| matches!(s, Stage::Sampling { .. })));
    assert!(!sampled.from_output);
    // Clamped inside the two-second clip.
    assert!(sampled.at_secs <= 1.5);
    // Both stills at the source's size, the encode at its capped one.
    let source = probe(&tools, &clip).expect("probe source");
    assert_eq!((sampled.width, sampled.height), source.display_size());
    assert_eq!(sampled.encoded_height, 120);
    assert!(sampled.original.exists() && sampled.compressed.exists());
    let ssim = sampled.ssim.expect("ssim");
    assert!(ssim > 0.0 && ssim < 1.0, "ssim {ssim}");
    assert!(sampled.rating.is_some());
    assert!(sampled.estimated_bytes.expect("estimate") > 0);

    let jobs = plan(&[clip], None, false);
    let summary = batch::run(&tools, &jobs, &opts, &cancel, |_| {});
    assert_eq!(summary.succeeded, 1);
    let request = Request {
        output: Some(jobs[0].output.clone()),
        at_secs: 1.0,
        ..request
    };
    let work = fresh_dir(&dir.join("preview")).expect("work dir");
    let finished =
        compare(&tools, &request, &work, &cancel, &mut |_| {}).expect("output comparison");
    assert!(finished.from_output);
    assert_eq!(finished.estimated_bytes, None);
    assert_eq!(finished.video_codec, "h264");
    assert!(finished.compressed.exists());
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn thumbnails_an_odd_sized_clip() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let dir = scratch("thumbnail");
    let clip = sample(&tools, &dir, 321, 241);
    let info = probe(&tools, &clip).expect("probe");
    let jpeg = thumbnail(&tools, &clip, &info).expect("thumbnail");
    // JPEG start-of-image marker.
    assert_eq!(&jpeg[..2], &[0xFF, 0xD8]);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
#[ignore = "needs ffmpeg and ffprobe"]
fn benchmarks_an_encode_rate_quickly() {
    let tools = Tools::locate().expect("ffmpeg on PATH");
    let opts = CompressOptions {
        codec: Codec::H264,
        preset: karui_core::options::Preset::Veryfast,
        ..Default::default()
    };
    let cancel = AtomicBool::new(false);
    let started = std::time::Instant::now();
    let rate = karui_core::estimate::benchmark(&tools, &opts, &cancel).expect("benchmark");
    // Any machine that can run CI encodes 720p faster than 1 Mpx/s.
    assert!(rate > 1e6, "rate {rate}");
    assert!(
        started.elapsed().as_secs() < 20,
        "took {:?}",
        started.elapsed()
    );

    cancel.store(true, std::sync::atomic::Ordering::Relaxed);
    assert!(matches!(
        karui_core::estimate::benchmark(&tools, &opts, &cancel),
        Err(karui_core::Error::Cancelled)
    ));
}
